import {StyleSheet} from 'react-native';
import {Colors} from './Colors';
import {BorderRadius, Spacing} from './Layout';

export const GameViewStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
        padding: Spacing.base,
    },
    cameraContainer: {
        flex: 1,
        backgroundColor: 'white',
        borderRadius: BorderRadius.xl,
        overflow: 'hidden',
        marginBottom: Spacing.base,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    compactCamera: {
        position: 'absolute',
        bottom: Spacing.base,
        right: Spacing.base,
        width: 100,
        height: 130,
        borderRadius: BorderRadius.lg,
        overflow: 'hidden',
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 3,
        borderColor: 'white',
    },
    compactCameraPressable: {
        position: 'absolute',
        bottom: Spacing.base,
        right: Spacing.base,
        width: 100,
        height: 130,
        borderRadius: BorderRadius.lg,
        overflow: 'hidden',
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 3,
        borderColor: Colors.emerald[500],
    }, expandedCamera: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        borderRadius: 0,
        overflow: 'hidden',
        backgroundColor: 'black',
        zIndex: 1000,
    },
    camera: {
        flex: 1,
    },
    cameraOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.05)',
    },
    expandButton: {
        position: 'absolute',
        top: 6,
        right: 6,
        backgroundColor: Colors.emerald[500],
        padding: 6,
        borderRadius: BorderRadius.sm,
        minWidth: 24,
        minHeight: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        backgroundColor: Colors.slate[800],
        padding: 8,
        borderRadius: BorderRadius.full,
        minWidth: 32,
        minHeight: 32,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },
    buttonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
    }, zoomContainer: {
        flexDirection: 'column',
        position: 'absolute',
        bottom: 100,
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: BorderRadius.xl,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        alignItems: 'center',
        minWidth: 200,
        maxWidth: 220,
    },
    zoomSlider: {
        width: 180,
        height: 40,
    },
    zoomButton: {
        backgroundColor: 'transparent',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: BorderRadius.lg,
        marginHorizontal: 2,
        minWidth: 40,
        alignItems: 'center',
    },
    activeZoom: {
        backgroundColor: Colors.emerald[500],
    }, zoomText: {
        color: Colors.slate[700],
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 4,
    },
    activeZoomText: {
        color: 'white',
    },
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: BorderRadius.xl,
        margin: 0,
        padding: Spacing.xl,
    },
    permissionMessage: {
        textAlign: 'center',
        fontSize: 16,
        color: Colors.slate[600],
        marginBottom: Spacing.lg,
        lineHeight: 24,
    },
    permissionButton: {
        backgroundColor: Colors.emerald[500],
        paddingHorizontal: Spacing.xl,
        paddingVertical: Spacing.lg,
        borderRadius: BorderRadius.lg,
        shadowColor: Colors.emerald[500],
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    }, permissionButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    zoomCameraContainer: {
        position: 'absolute',
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: 'white',
        shadowColor: '#000',
    },
    zoomCameraContainerCompact: {
        width: 100,
        height: 130,
        bottom: 16,
        right: 16,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 3,
        borderColor: '#10b981',
    },
    zoomCameraContainerExpanded: {
        width: '100%',
        height: '100%',
        top: 0,
        left: 0,
        borderRadius: 24,
        shadowOffset: {
            width: 0,
            height: 12,
        },
        shadowOpacity: 0.25,
        shadowRadius: 20,
        elevation: 20,
        borderWidth: 4,
        borderColor: 'white',
    },
    zoomSliderContainer: {
        flexDirection: 'column',
        position: 'absolute',
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: 16,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        alignItems: 'center',
        minWidth: 200,
        maxWidth: 220,
        left: '50%',
        marginLeft: -110,
    },
});
